- name: "system dirs created"
  file:
    path: "{{item}}"
    recurse: true
    state: directory
  become: true
  with_items:
    - "{{system_dirs}}"

- name: "user dirs created"
  file:
    path: "{{item}}"
    state: directory
    mode: 0750
  with_items:
    - "{{user_dirs}}"

- name: "base packages present"
  package:
    name: "{{item}}"
    state: present
  become: true
  with_items:
    - "{{base_packages}}"

- name: "/etc/hosts updated"
  template:
    src: "hosts.j2"
    dest: "/etc/hosts"
  become: true

- name: "pam limits set"
  pam_limits:
    domain: "{{item.domain}}"
    limit_type: "{{item.type}}"
    limit_item: "{{item.limit}}"
    value: "{{item.value}}"
  become: true
  with_items:
    - "{{pam_limits}}"
  
- name: "sysctl values set"
  sysctl:
    name: "{{item.name}}"
    value: "{{item.value}}"
    sysctl_set: yes
    reload: yes
  become: true
  with_items:
    - "{{sysctl_entries}}"

- name: "unneeded services disabled and stopped"
  systemd:
    name: "{{item}}"
    enabled: no
    state: stopped
  become: true
  ignore_errors: true
  with_items:
    - "{{disabled_services}}"

- name: "base services enabled and started"
  systemd:
    name: "{{item}}"
    enabled: yes
    masked: no
    state: started
  become: true
  with_items:
    - "{{base_services}}"
