- name: "sysctl values set"
  sysctl:
    name: "{{item.name}}"
    value: "{{item.value}}"
    sysctl_set: yes
    reload: yes
  become: true
  with_items:
    - "{{sysctl_entries}}"

- name: "kubernetes.repo updated"
  yum_repository:
    name: kubernetes
    description: Kubernetes Repository
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  become: true

- name: "required packages present"
  yum:
    name: "{{item}}"
    state: present
    update_cache: true
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  become: true

- name: "kubelet enabled and started"
  systemd:
    name: kubelet
    state: started
    enabled: yes
  become: true

