- hosts: all
  gather_facts: no
  serial: "100%"

  vars:
    - enable_epel: true
    - dns_servers:
      - 8.8.8.8
      - 8.8.4.4

  tasks:
    - include_role:
        name: alive

    - include_role:
        name: gather-facts

    - include_role:
        name: check-sudo

    - include_role:
        name: base

    - include_role:
        name: swap
      vars:
        enable_swap: false

    - include_role:
        name: rsyslog

    - include_role:
        name: td-agent-bit

    - include_role:
        name: docker

    - include_role:
        name: kubernetes
